export const VOICE_HINT_DISPLAY: Record<string, string> = {
  navegacion: 'navegación',
  accesibilidad: 'accesibilidad',
  lateral: 'lateral',
  salir: 'salir',
  cerrar: 'cerrar',
  carrusel: 'carrusel',
  izquierda: 'izquierda',
  derecha: 'derecha',
  juguemos: 'juguemos',
  siguiente: 'siguiente',
  evolucion: 'evolución',
  informacion: 'información',
  tipografia: 'tipografía',
  color: 'color',
  explicacion: 'explicación',
  vision: 'visión',
  voz: 'voz',
  teclado: 'teclado',
  lector: 'lector',
  escribir: 'escribir',
  guardar: 'guardar',
  limpiar: 'limpiar',
  maquina: 'máquina',
  kindle: 'Kindle',
  arriba: 'arriba',
  abajo: 'abajo',
  aceptar: 'aceptar',
  volumen: 'volumen',
  ver: 'ver',
  ocultar: 'ocultar',
  escuchar: 'escuchar',
  reproducir: 'reproducir',
  pausar: 'pausar',
  explorar: 'explorar',
  walkman: 'walkman',
  altavoz: 'altavoz',
  mundo: 'mundo',
  texto: 'texto',
  audio: 'audio',
  imagen: 'imagen',
  video: 'vídeo',
  musica: 'música',
  audiovisual: 'audiovisual',
  interactividad: 'interactividad',
};

export function voiceHintDisplay(key: string): string {
  return VOICE_HINT_DISPLAY[key] ?? key;
}
